name: docker-buildx

on:
  push:
    branches:
    - master
  watch:
    types: [started]
  schedule:
    - cron: "0 21 * * 5"

env:
  DOCKERHUB_USER: shantanugoel
  DOCKERHUB_REPO: docker-flexget
  ALPINE_VER: "3.12"
  LIBTORRENT_VER: "2.0.0"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=flexget_ver::$(pip3 search flexget | grep FlexGet | awk '{print $2}' | tr -d '()')
          echo ::set-output name=github_desc::$(curl -sX GET https://api.github.com/repos/wiserain/docker-flexget | jq -r .description)
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest,${{ steps.vars.outputs.flexget_ver }}
          dockerFile: Dockerfile
          buildArg: ALPINE_VER=${{ env.ALPINE_VER }},LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},FLEXGET_VER=${{ steps.vars.outputs.flexget_ver }}
          publish: true
          platform: linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
